## Simple examples

In [2]:
import pandas
import numpy as np
from sklearn.tree import DecisionTreeClassifier

In [3]:
x = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([0, 1, 0])
clf = DecisionTreeClassifier()
clf.fit(x, y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [4]:
importances = clf.feature_importances_
importances

array([0.25, 0.75])

In [5]:
np.isnan(x)

array([[False, False],
       [False, False],
       [False, False]])

## Programming Assignment

In [85]:
data = pandas.read_csv('titanic.csv', index_col='PassengerId')

In [86]:
data.replace(['male', 'female'], [1, 0], inplace=True)

In [87]:
tag = data[['Pclass','Fare','Age','Sex','Survived']]

In [88]:
#  check NaN
tag.isnull()

Pclass   Fare    Age    Sex  Survived
PassengerId                                       
1             False  False  False  False     False
2             False  False  False  False     False
3             False  False  False  False     False
4             False  False  False  False     False
5             False  False  False  False     False
...             ...    ...    ...    ...       ...
887           False  False  False  False     False
888           False  False  False  False     False
889           False  False   True  False     False
890           False  False  False  False     False
891           False  False  False  False     False

[891 rows x 5 columns]

In [89]:
 # NaN?
    tag.isnull().values.any() 

True

In [94]:
# data without NaN
tag = tag.dropna()

In [95]:
target_variable = tag['Survived']
attributes = tag[['Pclass','Fare','Age','Sex']]

In [96]:
target_variable = target_variable.to_numpy(dtype=None)
attributes = attributes.to_numpy(dtype=None)

In [97]:
# train
clf = DecisionTreeClassifier(random_state=241)
clf.fit(attributes, target_variable)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=241, splitter='best')

In [99]:
# the most important features
clf.feature_importances_

array([0.14000522, 0.30343647, 0.2560461 , 0.30051221])