## Simple examples

In [1]:
import pandas
import numpy as np
from sklearn.tree import DecisionTreeClassifier

In [2]:
x = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([0, 1, 0])
clf = DecisionTreeClassifier()
clf.fit(x, y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [3]:
importances = clf.feature_importances_
importances

array([0.25, 0.75])

In [4]:
np.isnan(x)

array([[False, False],
       [False, False],
       [False, False]])

## Programming Assignment

* Решающие деревья: Важность признаков

In [14]:
data = pandas.read_csv('titanic.csv', index_col='PassengerId')
data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [6]:
data.replace(['male', 'female'], [1, 0], inplace=True)

In [7]:
tag = data[['Pclass','Fare','Age','Sex','Survived']]

In [16]:
tag1 = data.loc[:, 'Pclass':'Age' ] 

In [9]:
#  check NaN
tag.isnull()

Empty DataFrame
Columns: []
Index: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, ...]

[891 rows x 0 columns]

In [89]:
 # NaN?
    tag.isnull().values.any() 

True

In [94]:
# data without NaN
tag = tag.dropna()

In [95]:
target_variable = tag['Survived']
attributes = tag[['Pclass','Fare','Age','Sex']]

In [96]:
target_variable = target_variable.to_numpy(dtype=None)
attributes = attributes.to_numpy(dtype=None)

In [97]:
# train
clf = DecisionTreeClassifier(random_state=241)
clf.fit(attributes, target_variable)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=241, splitter='best')

In [99]:
# the most important features
clf.feature_importances_

array([0.14000522, 0.30343647, 0.2560461 , 0.30051221])